### ISSUE TITLE
Not working with error message "E730: using List as a String"

### ISSUE THREAD

**Issue by wimstefan** [kg8m/vim-simple-align#2]
Hi,

After installing your plugin  I tried it with the examples you're giving in the README but I get this error message with different alignment examples:
``` viml
Error detected while processing function simple_align#align[10]..simple_align#tokenizer#lines_to_tokens_list:
line    1:
E730: using List as a String
E15: Invalid expression: a:lines->copy()->map("s:line_to_tokens(v:val, a:delimiter, a:options)")
```
My configuration:
``` viml
NVIM v0.5.0-dev+1168-g1df1098b0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```
... using packer.nvim with lua
``` viml
use 'kg8m/vim-simple-align'
```

Any configuration I've missed?

**Comment by kg8m** [comment]
@wimstefan Thank you for reporting. I updated the plugin. Can you try it?

**Comment by wimstefan** [comment]
Looking good 😏
Thanks for the fast fix 🙏🏼
